### ISSUE TITLE
`pastehub-clientSync' exit, when masterdb server is down.

### ISSUE THREAD

**Issue by kiyoka** [kiyoka/pastehub#3]
When masterdb server is down and notifier is alive.
pastehub-clientSync exit with ECONNREFUSED.

```
Info: server is stable:    1342787821=2012-07-20.12:37:00
Info: local  has new data
synchronizing...
/usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:762:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:762:in `open'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:762:in `block in connect'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:762:in `connect'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:744:in `start'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:557:in `start'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/pastehub-0.1.2/lib/pastehub/client.rb:23:in `getList'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/pastehub-0.1.2/bin/pastehub-clientSync:16:in `sync_db'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/pastehub-0.1.2/bin/pastehub-clientSync:76:in `syncMain'
from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/gems/1.9.1/gems/pastehub-0.1.2/bin/pastehub-clientSync:117:in `block in main'
```

**Comment by kiyoka** [comment]
I resolve this issue on version 0.1.1
