### ISSUE TITLE
`PastehubSync' abort on exception, when disconnect from masterdb.rb.

### ISSUE THREAD

**Issue by kiyoka** [kiyoka/pastehub#4]
Aborted when disconnected from server side ( server is masterdb.rb )

```
$ pastehub-clientSync
.
.
.
synchronizing...
Info: download 0 records.
Info:   upload 2 records.
  key=1346567794=2012-09-02.06:36:34=b730e4e3c594f46f75aa8aa59d643065b606a035
  key=1346567775=2012-09-02.06:36:15=51fa5866c8ce751dda8048f1f092c65274637e40
Info:   send signal to Emacs.
Emacs: no process found
Info: server has new data: 1346567775=2012-09-02.06:36:15=51fa5866c8ce751dda8048f1f092c65274637e40
Info: fetch one entry
synchronizing...
/usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/protocol.rb:141:in `read_nonblock': Connection reset by peer (Errno::ECONNRESET)
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:2562:in `read_status_line'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:2551:in `read_new'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:1319:in `block in transport_request'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:1316:in `transport_request'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:1293:in `request'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:1307:in `send_entity'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:1096:in `post'
    from /home/kiyoka/work/github/pastehub/lib/pastehub/client.rb:60:in `block in putValue'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:745:in `start'
    from /usr/local/stow/ruby-1.9.3-p194/lib/ruby/1.9.1/net/http.rb:557:in `start'
    from /home/kiyoka/work/github/pastehub/lib/pastehub/client.rb:59:in `putValue'
    from bin/pastehub-clientSync:55:in `block in syncDb'
    from bin/pastehub-clientSync:53:in `each'
    from bin/pastehub-clientSync:53:in `syncDb'
    from bin/pastehub-clientSync:135:in `syncMain'
    from bin/pastehub-clientSync:196:in `block in main'
```

**Comment by kiyoka** [comment]
fixed at 0.1.9.
