### ISSUE TITLE
`PastehubSync' abort on exception, when timeout occur.

### ISSUE THREAD

**Issue by kiyoka** [kiyoka/pastehub#5]
```
/usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/protocol.rb:146:in `rescue in rbuf_fill': Timeout::Error (Timeout::Error)
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:2562:in `read_status_line'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:2551:in `read_new'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1319:in `block in transport_request'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1316:in `transport_request'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1293:in `request'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1307:in `send_entity'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1096:in `post'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/gems/1.9.1/gems/pastehub-0.1.5/lib/pastehub/client.rb:201:in `block in putValue'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:745:in `start'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:557:in `start'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/gems/1.9.1/gems/pastehub-0.1.5/lib/pastehub/client.rb:200:in `putValue'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/gems/1.9.1/gems/pastehub-0.1.5/bin/PastehubSync:197:in `signalHandler'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/gems/1.9.1/gems/pastehub-0.1.5/bin/PastehubSync:224:in `block in main'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/gems/1.9.1/gems/pastehub-0.1.5/bin/PastehubSync:230:in `call'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/gems/1.9.1/gems/pastehub-0.1.5/bin/PastehubSync:230:in `join'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/gems/1.9.1/gems/pastehub-0.1.5/bin/PastehubSync:230:in `block in main'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/gems/1.9.1/gems/pastehub-0.1.5/bin/PastehubSync:230:in `each'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/gems/1.9.1/gems/pastehub-0.1.5/bin/PastehubSync:230:in `main'
    from /usr/local/stow/ruby-1.9.3-p286/lib/ruby/gems/1.9.1/gems/pastehub-0.1.5/bin/PastehubSync:234:in `<top (required)>'
    from /usr/local/bin/PastehubSync:23:in `load'
    from /usr/local/bin/PastehubSync:23:in `<main>'
```

**Comment by kiyoka** [comment]
fixed at 0.1.9.
